const bouquetFlowerData = [
  {
    name: "Valentine Love \n(Rose)",
    price: "75",
    size: [50, 75, 100],
    info: "Bouquet\n 50 pcs - ₹ price1\n75 pcs - ₹ price2\n 100 pcs - ₹ price3",
    image: `/productImages/flowerBouquet005.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Red Love \n(Rose)",
    price: "75",
    size: [10, 15, 30],
    info: "Bouquet\n 10 pcs - ₹ price1\n 15 pcs - ₹ price2\n 30 pcs - ₹ price3",
    image: `/productImages/flowerBouquet003.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Sunrise Yellow \n(Asiatic Lilies)",
    price: "250",
    size: [6, 10, 15],
    info: "Bouquet\n6 pcs - ₹ price1\n10 pcs - ₹ price2\n 15 pcs - ₹ price3",
    image: `/productImages/flowerBouquet001.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Orange \n(Carnation)",
    price: "60",
    size: [10, 15, 30],
    info: "Bouquet\n10 pcs - ₹ price1\n15 pcs - ₹ price2\n30 pcs - ₹ price3",
    image: `/productImages/flowerBouquet002.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Orange \n(Oriental Lilies)",
    price: "300",
    size: [6, 10, 15],
    info: "Bouquet\n6 pcs - ₹ price1\n10 pcs - ₹ price2\n 15 pcs - ₹ price3",
    image: `/productImages/flowerBouquet004.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "White \n(Carnation)",
    price: "60",
    size: [10, 15, 30],
    info: "Bouquet\n 10 pcs - ₹ price1\n 15 pcs - ₹ price2\n 30 pcs - ₹ price3",
    image: `/productImages/flowerBouquet006.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Pink \n(Oriental Lilies)",
    price: "300",
    size: [6, 10, 15],
    info: "Bouquet\n6 pcs - ₹ price1\n10 pcs - ₹ price2\n 15 pcs - ₹ price3",
    image: `/productImages/flowerBouquet007.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Blue \n (Orchid)",
    price: "130",
    size: [6, 10, 15],
    info: "Bouquet\n 6 pcs - ₹ price1\n 10 pcs - ₹ price2\n 15 pcs - ₹ price3",
    image: `/productImages/flowerBouquet008.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Red \n(Carnation)",
    price: "60",
    size: [10, 15, 30],
    info: "Bouquet\n 10 pcs - ₹ price1\n 15 pcs - ₹ price2\n 30 pcs - ₹ price3",
    image: `/productImages/flowerBouquet009.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "White \n(Asiatic Lilies)",
    price: "250",
    size: [6, 10, 15],
    info: "Bouquet\n6 pcs - ₹ price1\n10 pcs - ₹ price2\n 15 pcs - ₹ price3",
    image: `/productImages/flowerBouquet010.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Pink \n(Asiatic Lilies)",
    price: "250",
    size: [6, 10, 15],
    info: "Bouquet\n6 pcs - ₹ price1\n10 pcs - ₹ price2\n 15 pcs - ₹ price3",
    image: `/productImages/flowerBouquet011.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Pink \n (Orchid)",
    price: "130",
    size: [6, 10, 15],
    info: "Bouquet\n 6 pcs - ₹ price1\n 10 pcs - ₹ price2\n 15 pcs - ₹ price3",
    image: `/productImages/flowerBouquet012.jpeg`,
    productCategory: "Bouquet",
  },
];

export default bouquetFlowerData;
