const bouquetFlowerData = [
  {
    name: "Sunrise Yellow \n(Asiatic Lilies)",
    price: "₹ 900",
    info: "Bouquet\n6 pcs - ₹ 900\n10 pcs - ₹ 1499\n 15 pcs - ₹ 2250",
    image: `/productImages/flowerBouquet001.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Orange \n(Carnation)",
    price: "₹ 500",
    info: "Bouquet\n10 pcs - ₹ 500\n15 pcs - ₹ 675\n30 pcs - ₹ 1299",
    image: `/productImages/flowerBouquet002.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Red Love \n(Rose)",
    price: "₹ 500",
    info: "Bouquet\n 10 pcs - ₹ 500\n 15 pcs - ₹ 675\n 30 pcs - ₹ 1299",
    image: `/productImages/flowerBouquet003.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Orange \n(Oriental Lilies)",
    price: "₹ 1500",
    info: "Bouquet\n6 pcs - ₹ 1500\n10 pcs - ₹ 2499\n 15 pcs - ₹ 3700",
    image: `/productImages/flowerBouquet004.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Valentine Love \n(Rose)",
    price: "₹ 500",
    info: "Bouquet\n 50 pcs - ₹ 2399",
    image: `/productImages/flowerBouquet005.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "White \n(Carnation)",
    price: "₹ 500",
    info: "Bouquet\n 10 pcs - ₹ 500\n 15 pcs - ₹ 675\n 30 pcs - ₹ 1299",
    image: `/productImages/flowerBouquet006.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Pink \n(Oriental Lilies)",
    price: "₹ 1500",
    info: "Bouquet\n6 pcs - ₹ 1500\n10 pcs - ₹ 2499\n 15 pcs - ₹ 3700",
    image: `/productImages/flowerBouquet007.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Blue \n (Orchid)",
    price: "₹ 600",
    info: "Bouquet\n 6 pcs - ₹ 600\n 10 pcs - ₹ 999\n 15 pcs - ₹ 1499",
    image: `/productImages/flowerBouquet008.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Red \n(Carnation)",
    price: "₹ 500",
    info: "Bouquet\n 10 pcs - ₹ 500\n 15 pcs - ₹ 675\n 30 pcs - ₹ 1299",
    image: `/productImages/flowerBouquet009.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "White \n(Asiatic Lilies)",
    price: "₹ 900",
    info: "Bouquet\n6 pcs - ₹ 900\n10 pcs - ₹ 1499\n 15 pcs - ₹ 2250",
    image: `/productImages/flowerBouquet010.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Pink \n(Asiatic Lilies)",
    price: "₹ 900",
    info: "Bouquet\n6 pcs - ₹ 900\n10 pcs - ₹ 1499\n 15 pcs - ₹ 2250",
    image: `/productImages/flowerBouquet011.jpeg`,
    productCategory: "Bouquet",
  },
  {
    name: "Pink \n (Orchid)",
    price: "₹ 600",
    info: "Bouquet\n 6 pcs - ₹ 600\n 10 pcs - ₹ 999\n 15 pcs - ₹ 1499",
    image: `/productImages/flowerBouquet012.jpeg`,
    productCategory: "Bouquet",
  },
];

export default bouquetFlowerData;
