const boxFlowerData = [
  {
    name: "Mix Delight",
    price: "₹ 3499",
    info: "",
    image: `/productImages/flowerBox001.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Purple Delight",
    price: "₹ 4999",
    info: "",
    image: `/productImages/flowerBox002.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Spring Love",
    price: "₹ 3499",
    info: "",
    image: `/productImages/flowerBox003.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Blushing Beauty",
    price: "₹ 3999",
    info: "",
    image: `/productImages/flowerBox004.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Sweet Harmony",
    price: "₹ 3999",
    info: "",
    image: `/productImages/flowerBox005.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Floral Symphony",
    price: "₹ 3999",
    info: "",
    image: `/productImages/flowerBox006.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Blissful Symphony",
    price: "₹ 3999",
    info: "",
    image: `/productImages/flowerBox007.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Charming Love Roses",
    price: "₹ 4999",
    info: "",
    image: `/productImages/flowerBox008.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Pristine Beauty",
    price: "₹ 3999",
    info: "",
    image: `/productImages/flowerBox009.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Magical Dream",
    price: "₹ 3999",
    info: "",
    image: `/productImages/flowerBox010.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Spring Love",
    price: "₹ 3499",
    info: "",
    image: `/productImages/flowerBox011.jpeg`,
    productCategory: "Box Arrangement",
  },
  {
    name: "Simply Splendid",
    price: "₹ 4999",
    info: "",
    image: `/productImages/flowerBox012.jpeg`,
    productCategory: "Box Arrangement",
  },
];

export default boxFlowerData;
