import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../src/components/header";
import ProductPromotion from "../src/components/productPromotion";
import ProductCarousel from "../src/components/productCarousel";
import BrandLocation from "../src/components/brandLocation";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <ProductPromotion />
        <ProductCarousel productType={"box"} displayNumber={19} />
        <ProductCarousel productType={"basket"} displayNumber={8} />
        <ProductCarousel productType={"bunch"} displayNumber={5} />
        <ProductCarousel productType={"vase"} displayNumber={3} />
        <BrandLocation />
      </main>
    </>
  );
}
